### ISSUE TITLE
How to get the card nonce in react-native app?

### ISSUE THREAD

**Issue by harleenarora** [square/in-app-payments-react-native-plugin#37] opened 2019-12-04 09:06 UTC
I have worked on the latest version of React-native version. 

Requirement: User fill the card details (card number, expire month, expire year and cvv), on submit I have get the card nonce using square up using application Id and location id of square up. After get the nonce, pass this nonce to my custom rest api.

**Comment by okenshields** [comment] 2019-12-05 18:58
Hi Harleen,

This seems to be duplicate question? Please check comments in https://github.com/square/in-app-payments-react-native-plugin/issues/36

**Comment by StephenJosey** [comment] 2020-01-16 00:01
Duplicate of https://github.com/square/in-app-payments-react-native-plugin/issues/36 as mentioned above. Closing this.

**Closed by StephenJosey** 2020-01-16 00:01 UTC
Labels: duplicate, question
