### ISSUE TITLE
Set value of postalCode and postalCode not display to user?

### ISSUE THREAD

**Issue by harleenarora** [square/in-app-payments-react-native-plugin#41] opened 2019-12-10 03:14 UTC
Hi, I am trying to set the value of postal code and I user can't see the postal code. How to do this?

Code:
```
`const cardEntryConfig = {
	collectPostalCode: false,
	postalCode: '123456',
	squareLocationId: 'squareLocationId',
};
await SQIPCardEntry.startCardEntryFlow(
	cardEntryConfig,
	this.onCardNonceRequestSuccess,
	this.onCardEntryCancel,
);`
```

I will try this but its not working?

**Comment by StephenJosey** [comment] 2020-01-16 23:32
Looks to be a duplicate of https://github.com/square/in-app-payments-react-native-plugin/issues/39, closing.

**Closed by StephenJosey** 2020-01-16 23:32 UTC
Labels: duplicate, question
