### ISSUE TITLE
calling SQIPCore.setSquareApplicationId crashes the app

### ISSUE THREAD

**Issue by muhammadwafa** [square/in-app-payments-react-native-plugin#116] opened 2021-05-16 11:15 UTC
It's two day I am trying to solve crash problem for this plugin on react-native android

```
useEffect(()=> {

    const asyncFunc = async ()=> {
      try {

        await SQIPCore.setSquareApplicationId(""); // stop the app from launching.

      } catch (err) {

        console.log("###################", err);
      }
    };

    asyncFunc();

  }, []);
```

I linked as `react-native link react-native-square-in-app-payments`

```
"react-native-square-in-app-payments": "^1.5.0"
"react-native": "0.64.1",
```

**Comment by w0o** [comment] 2021-05-17 06:42
Same here, actual error seems to be related to an incompatibility (or basically broken Kotlin compilation):
java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;I)V in class Lkotlin/jvm/internal/MutablePropertyReference1Impl; or its super classes (declaration of 'kotlin.jvm.internal.MutablePropertyReference1Impl' appears in /data/app/~~6sSrcaAjxADixp2t8eMHLQ==/com.mycompany.myapp-yQeR0UBR4HPAwtlZsHYVtQ==/base.apk!classes3.dex)
        at sqip.InAppPaymentsSdk.<clinit>(Unknown Source:12)
        at sqip.InAppPaymentsSdk.setSquareApplicationId(Unknown Source:0)
        at sqip.react.SquareInAppPaymentsModule$1.run(SquareInAppPaymentsModule.java:45)
....

Does this support Android SDK 29+? 
Any thing we can do to resolve this?

**Comment by w0o** [comment] 2021-05-18 04:56
I managed to solve this by dropping downgrading react version and got it to work on Android SDK 29 but this is still a huge issue because I had to downgrade a few other expo and react packages.
Also, seems like the example app is broken in the same way and doesn't build on the latest React and/or Android SDK which confirms that the package will be unusable on current and future React versions.
Anything we can do to resolve this?

**Comment by muhammadwafa** [comment] 2021-05-18 04:59
Hi @w0o I solved this issue with downgrading this library to `v 1.4.0`, but I didn't downgrade the react and react-native version. So no everything works fine

**Comment by w0o** [comment] 2021-05-22 16:23
Thanks @muhammadwafa , I can confirm downgrading just this library to v1.4.0 without messing around with downgrading does in fact work. 
Since we are missing out on new important features (like Strong Customer Verification) I'm still interested in a response from the development team on how can we address the issue here.

**Comment by hukid** [comment] 2021-05-24 20:49
Yes, there is an issue with 1.5.0 and 1.5.1 and we are working on the fix. In the meantime, you can still use 1.4.0 with no problem. The Strong Customer Verification feature is fully supported in 1.4.0 now.

**Comment by vishwajitshep0815** [comment] 2021-11-12 09:03
Closing this issue as it is resolved in the latest release i.e 1.5.4.

**Closed by vishwajitshep0815** 2021-11-12 09:03 UTC
Labels: bug
