### ISSUE TITLE
Incorrectly detecting sandbox application ID

### ISSUE THREAD

**Issue by QuintonC** [square/in-app-payments-react-native-plugin#68] opened 2020-05-22 18:51 UTC
### Describe the issue
When attempting to process a test payment in the simulator we are presented with an error stating that we are using a production app id, but we are using a sandbox one (clearly given that sandbox keys are prefixed with sandbox).
  
  Here is the log:
  ```
 {"code": "USAGE_ERROR", "debugCode": "apple_pay_nonce_request_production_simulator", "debugMessage": "Apple Pay cannot be used in the simulator with a production Square application ID. Please use a Square sandbox application ID or test Apple Pay on a physical device.", "message": "Something went wrong. Please contact the developer of this application and provide them with this error code: production_simulator"}
  ```

### To Reproduce
  For example - 
  1. Initialize the SDK
  2. Initialize Apple Pay
  3. call `await SQIPApplePay.requestApplePayNonce` and use a valid credit card to pay

  Here the piece of code that reproduce the issue.
  ```javascript
    /**
     * Callback when successfully get the card nonce details for processig
     * apple pay sheet is still open and waiting for processing card nonce details
     * @param cardDetails
     */
    async onApplePayNonceRequestSuccess(cardDetails) {
        try {
            // take payment with the card nonce details
            // you can take a charge
            // await chargeCard(cardDetails);

            // you must call completeApplePayAuthorization to close apple pay sheet
            await SQIPApplePay.completeApplePayAuthorization(true);
        } catch (ex) {
            // handle card nonce processing failure

            // you must call completeApplePayAuthorization to close apple pay sheet
            await SQIPApplePay.completeApplePayAuthorization(false, ex.message);

            console.log(ex);
        }
    }

    /**
     * Callback when failed to get the card nonce
     * apple pay sheet is still open and waiting for processing error information
     */
    async onApplePayNonceRequestFailure(errorInfo) {
        // handle this error before close the apple pay sheet

        // you must call completeApplePayAuthorization to close apple pay sheet
        await SQIPApplePay.completeApplePayAuthorization(
            false,
            errorInfo.message
        );

        console.log(errorInfo);
    }

    /**
     * Callback when the apple pay sheet is closed after
     * call completeApplePayAuthorization or user tap to close apple pay sheet manually
     */
    onApplePayEntryComplete() {
        // handle the apple pay sheet closed event
    }

    async useDigitalWallet() {
        const totalPrice = await this.getTotalPrice();

        if (Platform.OS === 'ios') {
            const applePayConfig = {
                price: totalPrice,
                summaryLabel: 'Your Order',
                countryCode: 'US',
                currencyCode: 'USD',
                paymentType: SQIPApplePay.PaymentTypeFinal
            };

            try {
                await SQIPApplePay.requestApplePayNonce(
                    applePayConfig,
                    this.onApplePayNonceRequestSuccess,
                    this.onApplePayNonceRequestFailure,
                    this.onApplePayEntryComplete
                );
            } catch (ex) {
                console.error(ex);
            }
        }
    }
  ```

### Expected behavior
Apple Pay to finish successfully and return a valid token.

**Environment (please complete the following information):**
  - platform: iOS
  - OS and version: iOS13
  - dev environment: MacOS
  - In-App Payments Plugin version: 1.3.1

  In addition: Run `react-native info` in your terminal and copy the results here.
```System:
    OS: macOS 10.15.5
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 136.46 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 11.15.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.7.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 27, 28, 29
      Build Tools: 28.0.2, 28.0.3
      System Images: android-27 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-Q | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.3.1/11C505 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_222 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found
```

### Screenshots
![Simulator Screen Shot - iPhone 11 - 2020-05-22 at 14 48 12](https://user-images.githubusercontent.com/4250423/82699809-5584ee00-9c3b-11ea-9966-29e815c45db6.png)

### Additional context

This is a fairly fresh install of this plugin. I have followed all of the documentation for the plugin as well. The plugin is being initialized on component mount as well.

```
async componentDidMount() {
        await SQIPCore.setSquareApplicationId(
            'sandbox-REMOVED'
        );

        let digitalWalletEnabled = false;

        if (Platform.OS === 'ios') {
            await SQIPApplePay.initializeApplePay('REMOVED');
            digitalWalletEnabled = await SQIPApplePay.canUseApplePay();
        }

        this.setState({
            digitalWalletEnabled
        });
    }
```

**Comment by QuintonC** [comment] 2020-05-22 20:36
Uhh... so something that should be clarified is that to init the application you should use the legacy sandbox credentials. The legacy app id/credential is the only one that works for this.

Will this library be updated or is there something else that I will need to be looking for in the future?

**Comment by StephenJosey** [comment] 2020-05-22 20:49
Are you using the latest versions of the Android/iOS SDKs? The latest versions do support the new sandbox, only the really old versions support legacy sandbox ids as far as I know.

**Comment by QuintonC** [comment] 2020-05-22 21:18
> Are you using the latest versions of the Android/iOS SDKs? The latest versions do support the new sandbox, only the really old versions support legacy sandbox ids as far as I know.

I would assume so, yes. I just pulled and installed this SDK today.

```"react-native-square-in-app-payments": "^1.3.1",```

```pod 'RNSquareInAppPayments', :path => '../node_modules/react-native-square-in-app-payments'```

**Comment by DavidRagone** [comment] 2020-05-28 04:06
@QuintonC can you clarify what you mean by this, please?

> you should use the legacy sandbox credentials. The legacy app id/credential is the only one that works for this.

Is the issue you're describing above what occurs when you're using the legacy sandbox creds?

What happens when you use the new sandbox creds?

**Comment by QuintonC** [comment] 2020-05-28 04:38
> @QuintonC can you clarify what you mean by this, please?
> 
> 
> 
> > you should use the legacy sandbox credentials. The legacy app id/credential is the only one that works for this.
> 
> 
> 
> Is the issue you're describing above what occurs when you're using the legacy sandbox creds?
> 
> 
> 
> What happens when you use the new sandbox creds?

The issue described is what happens while using the new credentials. 

I’m able to get the square app to init only when using legacy sandbox creds.

**Comment by DavidRagone** [comment] 2020-05-28 05:43
Are you able to do these steps with the new credentials? 

> Initialize the SDK
> Initialize Apple Pay
> call await SQIPApplePay.requestApplePayNonce and use a valid credit card to pay

It sounds like you're saying it's only possible with the old ones (but then you hit the error).

**Comment by QuintonC** [comment] 2020-05-28 13:16
> Are you able to do these steps with the new credentials?
> 
> > Initialize the SDK
> > Initialize Apple Pay
> > call await SQIPApplePay.requestApplePayNonce and use a valid credit card to pay
> 
> It sounds like you're saying it's only possible with the old ones (but then you hit the error).

It appears that it initializes, but I am at the very least able to get the Apple Pay menu/Prompt to open. Upon clicking 'Pay with Passcode,' I receive the error stating that I cannot use production credentials.

**Comment by DavidRagone** [comment] 2020-05-30 16:00
Okay, can you share with me the application Id(s) that you're using, and I can dig into the logs on our end?

**Comment by QuintonC** [comment] 2020-06-01 16:15
> Okay, can you share with me the application Id(s) that you're using, and I can dig into the logs on our end?

Sure!

Legacy: sandbox-sq0idp-YqoV2uhDg67kVW1xtDHpIQ
Current: sandbox-sq0idb-dLO15xp0MzPTac3xtIP0TQ

**Comment by QuintonC** [comment] 2020-06-27 21:02
Chiming back in once again. I updated package.json to follow this repo here on Github instead of using NPM and I am still experiencing the same issues outlined above.

**Comment by wuiidl** [comment] 2020-07-01 21:38
As far I know Apple Pay does not work on a Simulator, it works fine for me with Square's sandbox on a real device.

**Comment by QuintonC** [comment] 2020-07-01 21:43
> As far I know Apple Pay does not work on a Simulator, it works fine for me with Square's sandbox on a real device.

When debugging it in the simulator you should get a notice that the credentials are not valid. That was my experience when logging and trying to track down what the issue was.

**Comment by jerearaujo03** [comment] 2021-03-09 17:28
Did you solved it? I'm facing the same issue. How can I get the legacy sandbox credentials?

**Comment by ggirotto** [comment] 2022-09-02 12:48
Facing the same issue! Anyone found a solution to this?

**Comment by CharmisG** [comment] 2022-11-11 09:36
@QuintonC @jerearaujo03 @ggirotto 
Are you guys still facing same issue ???

**Comment by CharmisG** [comment] 2022-12-07 05:19
Closing this issue but if you still find this problem please reopen this issue. Thank you.

**Closed by CharmisG** 2022-12-07 05:19 UTC
Labels: bug

**Comment by tobischw** [comment] 2023-02-22 20:51
Hi,

I am a developer working on the In-App Payments SDK at Square. I'd like to provide an update - the root cause of this issue stems from a bug introduced in our backend for handling sandbox interactions with Apple Pay. We are currently investigating the work required to fix this. For now, the recommendation is to test sandbox on a physical device, and that Apple Pay sandbox support on Simulator is currently unavailable.

Thank you for understanding!

**Comment by mistiansen** [comment] 2023-12-21 19:32
Hello, any updates on this? I am still encountering this issue when testing on Simulator.

**Comment by KlutchKyle** [comment] 2025-01-17 17:46
Still experiencing the same issue on Simulator on iOS. On Android Emulator, it also appears to be running in production mode, not accepting test cards with Google Pay.

**Comment by SaadFarooq-Dev** [comment] 2025-03-05 11:21
Any update on this?

**Comment by anfaslimx** [comment] 2025-04-05 09:03
anybody having application id invalid error

**Comment by leonaburime-ucla** [comment] 2025-04-09 22:55
I found the issue for web

https://sandbox.web.squarecdn.com/v1/square.js is  for dev and https://web.squarecdn.com/v1/square.js is for production.  I needed to dynamically import the correct one based on what environment im in.

**Comment by chikingsley** [comment] 2025-05-16 17:45
> I found the issue for web
> 
> [sandbox.web.squarecdn.com/v1/square.js](https://sandbox.web.squarecdn.com/v1/square.js) is for dev and [web.squarecdn.com/v1/square.js](https://web.squarecdn.com/v1/square.js) is for production. I needed to dynamically import the correct one based on what environment im in.

this is the actual fix. thanks man!
