### ISSUE TITLE
Payment not completed (Apple Pay)

### ISSUE THREAD

**Issue by rajatpillai** [square/in-app-payments-react-native-plugin#101] opened 2021-04-07 09:41 UTC
I am trying to make payment through apple pay and in return I am getting this error **Payment not completed**. I tried using both the **testing environment** and **production environment** but facing the same error.

**Library version:** 
- "react-native-square-in-app-payments": "^1.4.0",

Sharing the screenshot of the error which I am facing.

![IMG_20210407_150151__01](https://user-images.githubusercontent.com/35248779/113845666-625af380-97b3-11eb-98f0-0ed3cd04d08c.jpg)

**Comment by StephenJosey** [comment] 2021-04-07 15:22
Did you already go through this process: https://github.com/square/in-app-payments-react-native-plugin/blob/master/docs/enable-applepay.md? Specifically the first part where you need to upload the Apple Pay certificate to your Square Developer Dashboard.

**Comment by rajatpillai** [comment] 2021-04-07 15:30
> Did you already go through this process: https://github.com/square/in-app-payments-react-native-plugin/blob/master/docs/enable-applepay.md? Specifically the first part where you need to upload the Apple Pay certificate to your Square Developer Dashboard.
> 
> If so, what's your Square app id?

Yes, I have uploaded the apple pay certificate on Square Developer Dashboard.  

Square app id: sandbox-sq0idb-5p2pswXDioJLzsn8zGg5zg

**Comment by StephenJosey** [comment] 2021-04-08 20:48
I'm not seeing anything obvious on our side (no logs at all, so it's not even making it to the nonce generation). Can you try a different card and see if you still experience the same error?

**Comment by rajatpillai** [comment] 2021-04-09 08:27
I have tried the same with the real card as well as test cards but I am facing the same issue.

**Comment by rajatpillai** [comment] 2021-04-09 08:28
> I'm not seeing anything obvious on our side (no logs at all, so it's not even making it to the nonce generation). Can you try a different card and see if you still experience the same error?

I have tried the same with the real card as well as test cards but I am facing the same issue.

**Comment by rajatpillai** [comment] 2021-04-12 05:43
@StephenJosey any update?

**Comment by rajatpillai** [comment] 2021-04-14 09:31
> Thanks for confirming. I will escalate on our side to see if we can dig in.

Any luck on this?

**Comment by rajatpillai** [comment] 2021-04-16 05:51
> > Thanks for confirming. I will escalate on our side to see if we can dig in.
> 
> Any luck on this?

Hi @StephenJosey,
 any luck on this?

**Comment by StephenJosey** [comment] 2021-04-16 16:10
Apologies for delay. I have not heard back from the team. I'll be sure to update this once I have more information.

**Comment by vatsal-gadhiya-searce** [comment] 2021-04-22 07:09
@StephenJosey I am also facing the same issue. Any update?

**Comment by StephenJosey** [comment] 2021-04-26 15:53
Hi @rajatpillai would you be able to share how you're creating the apple pay request? eg:
```
await SQIPApplePay.requestApplePayNonce(
          {
            price: '1.00',
            summaryLabel: 'Test Item',
            countryCode: 'US',
            currencyCode: 'USD',
            paymentType: SQIPApplePay.PaymentTypeFinal,
          },
 ```
@vatsal-gadhiya-searce was able to find this issue was caused by passing `UK` instead of `GB` and I'm wondering if it's the same issue as you?

**Comment by rajatpillai** [comment] 2021-04-29 04:28
> Hi @rajatpillai would you be able to share how you're creating the apple pay request? eg:
> 
> ```
> await SQIPApplePay.requestApplePayNonce(
>           {
>             price: '1.00',
>             summaryLabel: 'Test Item',
>             countryCode: 'US',
>             currencyCode: 'USD',
>             paymentType: SQIPApplePay.PaymentTypeFinal,
>           },
> ```
> 
> @vatsal-gadhiya-searce was able to find this issue was caused by passing `UK` instead of `GB` and I'm wondering if it's the same issue as you?

  const applePayConfig = {
        price: totalValue,
        summaryLabel: card.name,
        countryCode: 'US',
        currencyCode: 'USD',
        paymentType: SQIPApplePay.PaymentTypeFinal,
      };
      
      The above is my config but facing the same issue.

**Comment by rajatpillai** [comment] 2021-04-29 06:55
@StephenJosey it will be great if any team member can come for a screen share call, where he can verify the things and can efficiently debug the issue. I have a deadline and it will be great if I can get support from the Square team.

Thanks

**Comment by janet-rivas** [comment] 2021-11-05 11:53
I have the same issue, this is the error that I'm getting -

```
{
    "code": "USAGE_ERROR",
    "message": "Something went wrong. Please contact the developer of this application and provide them with this error code: unexpected",
    "debugCode": "apple_pay_nonce_request_unexpected",
    "debugMessage": "Square In-App Payments SDK encountered an unexpected error. Please contact Square developer support via https://squareup.com/help/contact"
}



```

and my configuration to request requestApplePayNonce
 
```

const applePayConfig = {
        price: '1.00',
        summaryLabel: 'EVolution Charging',
        countryCode: 'US',
        currencyCode: 'USD',
        paymentType: SQIPApplePay.PaymentTypePending,
      };
      try {
        await SQIPApplePay.requestApplePayNonce(
          applePayConfig,
          this.onApplePayNonceRequestSuccess,
          this.onApplePayNonceRequestFailure,
          this.onApplePayEntryComplete,
        );
      } catch (ex) {
        // Handle InAppPaymentsException
        console.log('Exception', ex);
      }
```

It was working before the only thing is It could be is I upgrade xcode version from 12.5 to 13 and this is happening in  "react-native-square-in-app-payments": "^1.4.0", 1.6.0 and 1.7.0

This in my react native info 
System:
    OS: macOS 11.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 138.25 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.6 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.0.0 - /usr/local/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 27, 28, 29, 30
      Build Tools: 28.0.3, 29.0.0, 29.0.2, 29.0.3, 30.0.2
      System Images: android-26 | Google APIs Intel x86 Atom_64, android-27 | Intel x86 Atom_64, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64, android-28 | Google X86_ARM Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.1 => 17.0.1 
    react-native: ^0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found


![image](https://user-images.githubusercontent.com/28309400/140505544-083f1768-c5f1-474e-adb3-679de4fa0015.png)

Please let me know if you fin the fix for it

**Comment by sudzy-group** [comment] 2022-04-13 19:43
Any resolution for this issue? it just started happening to specific customers and I am wondering if you know how to resolve this?

**Comment by sudzy-group** [comment] 2022-04-13 20:14
Just to follow up, looks that the certificate on Square admin was removed from me. Not sure if it can help someone else. I don't think it's a Square issue.

**Comment by hukid** [comment] 2022-11-22 17:45
@sudzy-group close this issue, please let us know if this is still a problem.

**Comment by sudzy-group** [comment] 2022-11-22 17:48
@hukid  - can I speak with someone to show them the issue?

**Comment by hukid** [comment] 2022-11-22 17:49
@sudzy-group thanks for the quick response! I'll connect you with someone.

**Comment by sudzy-group** [comment] 2022-11-22 18:02
Thank you @hukid , looking forward

**Comment by plinio-square** [comment] 2023-07-11 21:23
Hi @sudzy-group are you still seeing this issue?

**Comment by kirstiedownie** [comment] 2024-01-22 16:32
Closing as we have not gotten a follow up from the developer. Feel free to reopen if you are still facing this issue.

**Closed by kirstiedownie** 2024-01-22 16:32 UTC
Labels: bug
